#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "apt",                   "= 1.2.0"
cookbook "build-essential",       "= 1.0.0"
cookbook "chef_handler",          "= 1.0.6"
cookbook "database",              "= 1.3.12"
cookbook "mysql",                 "= 1.3.0"
cookbook "apache2",               "= 1.0.8"
cookbook "php",                   "= 1.0.2"
cookbook "beanstalkd",            "= 0.0.2"
cookbook "python",                "= 1.0.8"
cookbook "minitest-handler",      "= 0.1.0"
cookbook "rsync",                 "= 0.7"
cookbook "screen",                "= 0.7"
cookbook "git",                   "= 0.9.0"
cookbook "openssh",               "= 1.3.2"
cookbook "postfix",               "= 1.0.0"
cookbook "user",                  "= 0.2.12"

cookbook 'locales',
  :git => 'git://github.com/typo3-cookbooks/locales.git'

cookbook 'chef-solo-search',
  :git => 'git://github.com/edelight/chef-solo-search.git'

cookbook 'site-docstypo3org',
  :git => 'https://github.com/TYPO3-cookbooks/site-docstypo3org.git'
